### ISSUE TITLE
Productionalize the Meta-DAO

### ISSUE THREAD

**Issue by metaproph3t** [metaDAOproject/MetaDAO#11]
## Overview

Bring the Meta-DAO to production.

- [ ] Search for / create a CLOB that provides TWAPs.
- [ ] Integrate the CLOB into the Meta-DAO core code.
- [ ] Deploy the Meta-DAO.
